### ISSUE TITLE
Math inline

### ISSUE THREAD

**Issue by juh2** [aksdb/pandoc-xhtml#1]
I have a small text with inline math. Is it somehow possible to use math in pandoc-xhtml?

I played around with

```

\xmlsetsetup{\xmldocument}
        {span[contains(@class, 'math inline')]}
        {xml:math}
```

and

```
\startxmlsetups xml:math
    \bgroup\math\xmlflush{#1}\egroup
\stopxmlsetups
```

But I hade no luck. I am also not sure whether with \math ConTeXt would use a math font

In fact I see "main::837" where I expect the math sign.

**Comment by juh2** [comment]
I played around with

```
\xmlsetsetup{\xmldocument}
        {span[contains(@class, 'math inline')]}
        {xml:math}
```

and

```
\startxmlsetups xml:math
    \bgroup\math\xmlflush{#1}\egroup
\stopxmlsetups
```

But I hade no luck. I am also not sure whether with \math ConTeXt would use a math font.

**Comment by aksdb** [comment]
I'll take a look at it. It will probably boil down to supporting `<span class="LaTeX">...</span>` and simply running the inner text as TeX (in our case ConTeXt, but anyway ... ;-)).
Then you can process markdown code with `pandoc --latexmathml`.

**Comment by aksdb** [comment]
Support for math added in commit b38cb97. You can use the pandoc default now, but this may look ugly (or like nothing at all) if the equation is simple, because pandoc will then replace entities on its own.
To always render via TeX, pass the `--gladtex` option to pandoc. It will then create `<eq>` tags, that are now recognized by pandoc-xhtml.

**Comment by juh2** [comment]
Thanks. The --gladtex option is needed not only for the `<eq>` tag. In my usecase a inline `$\bigwedge$` is translated to `<span class="math inline">⋀</span>` in tmp.xml. If I don't use --gladtex I get no output, only with --gladtex I get the bigwedge. Obviously, there is more to say about --gladtex than stated in http://pandoc.org/README.h

**Comment by aksdb** [comment]
Your example shows what I meant. Evidently I didn't articulate that pretty good ;-)
Pandoc by default (without any additional parameters) tries to translate math into unicode signs, when you output to HTML. bigwedge, rightarrow, etc. seem to fall under that category. Also simple stuff like "1+2".
`--gladtex` is therefore more or less a workaround, since this is the only math-mode I found that did not add any overhead or preprocess the output. `--latexmathml` came close too, since it leaves the TeX code intact. Unfortunately it also adds a lot of javascript code into the HTML. This doesn't matter to ConTeXt, but I don't like it :)
In the Pandoc README you can find these information in the section about `tex_math_dollars`, where the output to the different formats is explained.
